---
- name: Deploy Apache and copy files
  hosts: "*"
  become: yes
  tasks:
  - name: Install Apache
    become: true
    apt:
      name: apache2
      state: present

  - name: Copy files
    copy:
      src: ../../src/
      dest: /var/www/html/
      owner: www-data
      group: www-data
      mode: 0755